version: '3.8'

services:
  product-service1:
    build: .
    image: product-service
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: bash -c "dotnet ef database update && dotnet ProductService.dll"
    
  product-service2:
    build: .
    image: product-service
    ports:
      - "8082:8080"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: bash -c "dotnet ef database update && dotnet ProductService.dll"

  rabbitmq:
    image: rabbitmq:3.11.5-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data

volumes:
  product-db-data:
