version: '3.8'

services:
    product-service1:
        build: .
        image: product-service
        ports:
            - "8081:8080"
        depends_on:
            - rabbitmq
            - postgres

    product-service2:
        build: .
        image: product-service
        ports:
            - "8082:8080"
        depends_on:
            - rabbitmq
            - postgres

    rabbitmq:
        image: rabbitmq:3.11.5-management
        ports:
            - "5672:5672"
            - "15672:15672"

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: product_db
        volumes:
            - product-db-data:/var/lib/postgresql/data

volumes:
    product-db-data: